In [1]:
from Classical.Linear_Regression import LinearRegression
from Classical.Logistic_Regression import LogisticRegression
from Classical.NearestNeighbour import KNN
from Classical.Naive_Bayes import NaiveBayes
from Classical.Support_Vectors import SVC, SVR
from Classical.Trees.DecisonTree import Decision_Tree
from Classical.Trees.RandomForest import Random_Forest
from Classical.Trees.AdaBoost import  Ada_Boost
from Classical.Trees.GradientBoost import Gradient_Boost
from Classical.metrics import mean_absolute_error, mean_squared_error,accuracy
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt
%matplotlib inline

**Linear regression**

In [2]:
X,y = datasets.make_regression(n_samples=100,n_features=7,noise=20,random_state=4)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
regressor = LinearRegression(lr=0.01)
regressor.fit(X_train,y_train)
lr_predict = regressor.predict(X_test)
mae = mean_absolute_error(y_test,lr_predict._data)
print(mae)

Beginning Training: fitting data of shape (80, 7) to Labels
Training complete!!!
14.159202822035066 


**Logistic regression**

In [3]:
bc = datasets.load_breast_cancer()
X,y = bc.data, bc.target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
regressor = LogisticRegression(lr= 0.001)
regressor.fit(X_train,y_train)
predict = regressor.predict(X_test)
acc = accuracy(y_test, predict)
print(acc)

Beginning Training: fitting data of shape (455, 30) to Labels


c:\Users\PC\Desktop\Lattice library\Lattice\Lattice_mathcomp.py:65: RuntimeWarning: overflow encountered in exp
  val._data = np.exp(val._data.astype(float))


Training complete!!!
0.8947368421052632 


**K-nearest neighbour classification**

In [4]:
iris = datasets.load_iris()
X,y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
knn = KNN(k=2)
knn.fit(X_train,y_train)
predict = knn.predict(X_test)
acc = accuracy(y_test, predict)
print(acc)

1.0 


**K-nearest neighbour regression**

In [5]:
X,y = datasets.make_regression(n_samples=500,n_features=7,noise=20,random_state=4)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
knn = KNN(k=7,mode='rgs')
knn.fit(X_train,y_train)
predict = knn.predict(X_test)
mse = mean_squared_error(y_test, predict)
print(mse)

3400.129842411957 


**Naive Bayes**

In [6]:
X,y = datasets.make_classification(n_samples=1000,n_features=6,n_classes=2,n_informative=4,n_redundant=2,random_state=42) 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
nb = NaiveBayes()
nb.fit(X_train,y_train)
predict = nb.predict(X_test)
acc = accuracy(y_test,predict)
print(acc)

0.455 


c:\Users\PC\Desktop\Lattice library\Lattice\Lattice_type.py:491: RuntimeWarning: divide by zero encountered in divide
  data = a._data / b._data
c:\Users\PC\Desktop\Lattice library\Lattice\Lattice_type.py:491: RuntimeWarning: invalid value encountered in divide
  data = a._data / b._data


**Support Vector Machines Classification**

In [7]:
X,y = datasets.make_classification(n_samples=200,n_features=4,n_classes=2,n_informative=2,n_redundant=2,n_clusters_per_class=1,random_state=1234) 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
svc = SVC(n_iters = 50)
svc.fit(X_train,y_train)
predict = svc.predict(X_test)
acc = accuracy(y_test,predict)
print(acc)

0.975 


**Support Vector Machines Regression**

In [8]:
X,y = datasets.make_regression(n_samples=70,n_features=7,noise=20,random_state=4)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
svr = SVR(learning_rate = 0.001,i_loss=0.001,n_iters=100)
svr.fit(X_train,y_train)
predict = svr.predict(X_test)
mse = mean_squared_error(y_test, predict)
mse

580.3954018219258 

**Decision Trees Classification**

In [9]:
bc = datasets.load_breast_cancer()
X,y = bc.data, bc.target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
dt= Decision_Tree(max_depth = 30)
dt.fit(X_train,y_train)
predict = dt.predict(X_test)
acc = accuracy(y_test,predict)
print(acc)

0.9298245614035088 


**Decision Trees Regression**

In [10]:
X,y = datasets.make_regression(n_samples=300,n_features=4,noise=20,random_state=4)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
dt= Decision_Tree(max_depth = 200,mode='rgs',)
dt.fit(X_train,y_train)
predict = dt.predict(X_test)
mse = mean_squared_error(y_test, predict)
mse

3268.746456163781 

**Random Forest classification**

In [11]:
X,y = datasets.make_classification(n_samples=500,n_features=6,n_classes=5,n_informative=5,n_redundant=1,n_clusters_per_class=1,random_state=12) 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=12)
rf= Random_Forest(n_trees=30,max_depth = 20)
rf.fit(X_train,y_train)
predict = rf.predict(X_test)
acc = accuracy(y_test,predict)
print(acc)

0.81 


**Random Forest regression**

In [12]:
X,y = datasets.make_regression(n_samples=500,n_features=3,noise=20,random_state=4)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
rf= Random_Forest(n_trees=100, max_depth = 60,mode='rgs')
rf.fit(X_train,y_train)
predict = rf.predict(X_test)
mse = mean_squared_error(y_test, predict)
mse

590.6669862656421 

**AdaBoost classification**

In [13]:
X,y = datasets.make_classification(n_samples=200,n_features=10,n_classes=2,n_clusters_per_class=1,random_state=12) 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
ad = Ada_Boost(n_clf=5)
ad.fit(X_train,y_train)
predict = ad.predict(X_test)
acc = accuracy(y_test,predict)
acc

0.825 

**Gradient Boost Regression**

In [14]:
X,y = datasets.make_regression(n_samples=500,n_features=3,noise=20,random_state=4)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
gb = Gradient_Boost(n_learners=10,mode='rgs',gamma=0.1,max_depth=5)
gb.fit(X_train,y_train)
predict = gb.predict(X_test)
mse = mean_squared_error(y_test, predict)
mse

3668.5001015174385 

**Gradient Boost Binary Classification**

In [8]:
X,y = datasets.make_classification(n_samples=500,n_features=5,n_classes=2,n_clusters_per_class=1,random_state=12) 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
gb = Gradient_Boost(n_learners=5,mode='cls',gamma=0.1,max_depth=10)
gb.fit(X_train,y_train)
predict = gb.predict(X_test)
acc = accuracy(y_test,predict)
acc

0.93 

In [1]:
from Classical.Trees.GradientBoost import Gradient_Boost
from Classical.metrics import mean_absolute_error, mean_squared_error,accuracy
from sklearn.model_selection import train_test_split
from sklearn import datasets
X,y = datasets.make_classification(n_samples=50,n_features=5,n_classes=3,n_clusters_per_class=1,random_state=12) 
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1234)
gb = Gradient_Boost(n_learners=10,mode='cls',gamma=0.1,max_depth=15,mclass=True)
gb.fit(X_train,y_train)
predict = gb.predict(X_test)
acc = accuracy(y_test,predict)
acc

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class '

TypeError: float() argument must be a string or a real number, not 'Decision_Tree'

In [ ]:
y_test,predict

(array([2, 0, 1, 2, 2, 0, 2, 0, 1, 0]), Lt_tensor([0 0 1 0 0 0 0 0 0 0] ))

In [ ]:
from main import *
x = column_stack([[1,2,3],[4,5,6],[7,8,9]])
x

Lt_tensor([[1 4 7]
 [2 5 8]
 [3 6 9]] )